version: "3.9"
services:
  nodejs:
    image: node:lts-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "yarn && npx prisma migrate dev --name init && yarn dev"
    ports:
      - "3000:3000"
